export enum WebSocketMessageAction {
  START_PRESENTER = 'START_PRESENTER',
  NEXT_ITEM_IN_PRESENTER = 'NEXT_ITEM_IN_PRESENTER',
  PREV_ITEM_IN_PRESENTER = 'PREV_ITEM_IN_PRESENTER',
  PRESENTER_FINISHED = 'PRESENTER_FINISHED',
  REFRESH_COMPONENT = 'REFRESH_COMPONENT',
}

export interface WebSocketMessage {
  action: WebSocketMessageAction
  data: object
}
